Fixed bash test script

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -1,29 +1,17 @@
-#!/bin/bash
-test_dir='tests';
-ls -f $test_dir | while read -r file; do
-	if [[ $file == '.' || $file == '..' ]]; then
-		continue
-	fi
+#!/usr/bin/env bash
+mkdir -p "outputs"
+for file in tests/*; do
+	[ -e "$file" ] || continue
+	output_file="outputs/${file##*/}"
 
-	# make sure that we have the "outputs" folder
-	mkdir -p "outputs"
+	bin/json_merger "$file" --javascript --pretty > "$output_file"
 
-	bin/json_merger "$test_dir/$file" --javascript --pretty > "outputs/$file"
-
-	if [[ ! -f "expected_outputs/$file" ]]; then
-		echo "$file result doesn't exists"
-		continue
-	fi
-
-	result=`diff expected_outputs/$file outputs/$file`
-
-	if [[ "$result" == "" ]]; then
-	  echo "$file passed test"
+	result=$(diff "expected_outputs/${file##*/}" "$output_file")
+	if [ $? -eq 0 ]; then
+		echo "$file passed test"
 	else
-	  echo "$file failed"
-	  echo "$result"
-	  exit 1;
+		>&2 echo "$file failed"
+		>&2 echo "$result"
+		exit 1
 	fi
 done
-
-exit 0;
